DS-278 client given read access to staging stuff

diff --git a/irods/files/cmd-common/de-archive-data b/irods/files/cmd-common/de-archive-data
--- a/irods/files/cmd-common/de-archive-data
+++ b/irods/files/cmd-common/de-archive-data
@@ -29,6 +29,11 @@ main()
   local execId="$4"
   local appId="$5"
 
+  if ! ichmod -M read "$clientUser" "$stagePath" 2>&1
+  then
+    printf 'WARN: Unable to give %s read access to %s\n' "$clientUser" "$stagePath"
+  fi
+  
   if ! clientUserName="$clientUser" icp -K -Q "$stagePath" "$archivePath"
   then
     return 1
diff --git a/irods/files/cmd-common/de-create-collection b/irods/files/cmd-common/de-create-collection
--- a/irods/files/cmd-common/de-create-collection
+++ b/irods/files/cmd-common/de-create-collection
@@ -6,10 +6,12 @@
 #  de-create-collection clientUser collPath analId execId
 #
 # PARAMETERS:
-#  clientUser
-#  collPath    The logical path to the collection to create
-#  execId      The Id of the DE app execution that is generating the collection
-#  appId       The Id of the DE app that was executed
+#  clientUser   The iRODS user name of the client who owns the data
+#  stagePath    The staging path of the object being moved.
+#  archivePath  The path to where the object is moved.
+#  execId       The Id of the DE app execution that is generating the data
+#               object
+#  appId        The Id of the DE app that was executed
 
 
 main()
@@ -21,17 +23,23 @@ main()
   fi
 
   local clientUser="$1"
-  local collPath="$2"
-  local execId="$3"
-  local appId="$4"
+  local stagePath="$2"
+  local archivePath="$3"
+  local execId="$4"
+  local appId="$5"
 
-  if ! clientUserName="$clientUser" imkdir -p "$collPath"
+  if ! ichmod -M read "$clientUser" "$stagePath" 2>&1
+  then
+    printf 'WARN: Unable to give %s read access to %s\n' "$clientUser" "$stagePath"
+  fi
+
+  if ! clientUserName="$clientUser" imkdir -p "$archivePath"
   then
     return 1
   fi
 
   local kvs
-  kvs=$(query_kvs "$collPath")
+  kvs=$(query_kvs "$archivePath")
 
   if [[ "$kvs" =~ CAT_NO_ROWS_FOUND: ]]
   then
@@ -42,9 +50,9 @@ main()
 
   if ! [[ "$kvs" =~ $execKV ]]
   then
-    if ! imeta adda -c "$collPath" ipc-execution-id "$execId" UUID 2>&1
+    if ! imeta adda -c "$archivePath" ipc-execution-id "$execId" UUID 2>&1
     then
-      printf 'WARN: Unable to assign execution Id %s to collection %s\n' "$execId" "$collPath"
+      printf 'WARN: Unable to assign execution Id %s to collection %s\n' "$execId" "$archivePath"
     fi
   fi
 
@@ -52,9 +60,9 @@ main()
 
   if ! [[ "$kvs" =~ $appKV ]]
   then
-    if ! imeta adda -c "$collPath" ipc-analysis-id "$appId" UUID 2>&1
+    if ! imeta adda -c "$archivePath" ipc-analysis-id "$appId" UUID 2>&1
     then
-      printf 'WARN: Unable to assign app Id %s to collection %s\n' "$appId" "$collPath"
+      printf 'WARN: Unable to assign app Id %s to collection %s\n' "$appId" "$archivePath"
     fi
   fi
 }
