update irods_runtime_init to ensure uuids

diff --git a/irods/irods_runtime_init.yml b/irods/irods_runtime_init.yml
--- a/irods/irods_runtime_init.yml
+++ b/irods/irods_runtime_init.yml
@@ -34,26 +34,6 @@
         admin_password: "{{ _irods_clerver_password }}"
         zone: "{{ _irods_zone_name }}"
 
-    - name: Ensure that the starting collections get UUIDs
-      delegate_to: localhost
-      become: false
-      ansible.builtin.command:
-        cmd: "imeta ls -C {{ item }} | grep -q 'UUID' || imeta add -C {{ item }} UUID $(uuidgen -t)"
-        stdin: "{{ _irods_admin_password }}"
-      with_items:
-        - /{{ _irods_zone_name }}
-        - /{{ _irods_zone_name }}/home
-        - /{{ _irods_zone_name }}/home/{{ _irods_clerver_user }}
-        - /{{ _irods_zone_name }}/home/shared
-        - /{{ _irods_zone_name }}/trash
-        - /{{ _irods_zone_name }}/trash/home
-        - /{{ _irods_zone_name }}/trash/home/{{ _irods_clerver_user }}
-        - /{{ _irods_zone_name }}/trash/home/shared
-      # changed_when: "'UUID' not in cmd_result.stdout"
-      changed_when: false
-      register: cmd_result
-      ignore_errors: false
-
     - name: Ensure CyVerse curated collection base collection exists
       become: false
       delegate_to: localhost
@@ -66,6 +46,41 @@
         admin_user: "{{ _irods_clerver_user }}"
         admin_password: "{{ _irods_clerver_password }}"
         zone: "{{ _irods_zone_name }}"
+
+    - name: Check if collections have ipc_UUID using iquest and store missing ones
+      ansible.builtin.shell:
+        executable: /bin/bash
+        cmd: |
+          set -o pipefail
+          output=$(iquest '%s' "select META_COLL_ATTR_VALUE where META_COLL_ATTR_NAME = 'ipc_UUID' and COLL_NAME = '{{ item }}'")
+            if [[ "$output" == *"CAT_NO_ROWS_FOUND"* ]] || [[ -z "$output" ]]; then
+            echo "UUID not found for collection: {{ item }}: $output"
+          fi
+      with_items:
+        - /{{ _irods_zone_name }}
+        - /{{ _irods_zone_name }}/home
+        - /{{ _irods_zone_name }}/home/{{ _irods_clerver_user }}
+        - /{{ _irods_zone_name }}/home/shared
+        - /{{ _irods_zone_name }}/trash
+        - /{{ _irods_zone_name }}/trash/home
+        - /{{ _irods_zone_name }}/trash/home/{{ _irods_clerver_user }}
+        - /{{ _irods_zone_name }}/trash/home/shared
+      register: uuid_check
+      changed_when: false
+      ignore_errors: true
+
+    - name: Store collections without ipc_UUID
+      ansible.builtin.set_fact:
+        collections_without_uuid: "{{ uuid_check.results | selectattr('stdout', 'search', 'UUID not found') | map(attribute='item') | list }}"
+
+    - name: Add UUID to collections without ipc_UUID
+      ansible.builtin.shell: |
+        uuid=$(uuidgen -t)
+        imeta set -C {{ item }} ipc_UUID $uuid
+      with_items: "{{ collections_without_uuid }}"
+      changed_when: true
+      register: cmd_result
+      ignore_errors: false
 
     - name: Initialize rodsadmin perms
       when: init_rodsadmin_perms | d(false)
@@ -120,7 +135,7 @@
     - name: Ensure anonymous user has read access to required collections
       delegate_to: localhost
       become: false
-      no_log: true
+      # no_log: true
       irods_permission:
         subject: anonymous
         permission: read
@@ -139,7 +154,7 @@
     - name: Start quota usage computation
       delegate_to: localhost
       become: false
-      no_log: true
+      # no_log: true
       ansible.builtin.command:
         cmd: >
           irule --rule-engine-plugin-instance=irods_rule_engine_plugin-irods_rule_language-instance
@@ -151,7 +166,7 @@
     - name: Start storage free space determination
       delegate_to: localhost
       become: false
-      no_log: true
+      # no_log: true
       ansible.builtin.command:
         cmd: >
           irule --rule-engine-plugin-instance=irods_rule_engine_plugin-irods_rule_language-instance
@@ -163,7 +178,7 @@
     - name: Start trash removal
       delegate_to: localhost
       become: false
-      no_log: true
+      # no_log: true
       ansible.builtin.command:
         cmd: >
           irule --rule-engine-plugin-instance=irods_rule_engine_plugin-irods_rule_language-instance
diff --git a/irods/tests/irods_runtime_init.yml b/irods/tests/irods_runtime_init.yml
--- a/irods/tests/irods_runtime_init.yml
+++ b/irods/tests/irods_runtime_init.yml
@@ -42,8 +42,11 @@
         executable: /bin/bash
         cmd: |
           set -o pipefail
-          iquest '%s' "select META_DATA_ATTR_VALUE where META_DATA_ATTR_NAME = 'UUID' and COLL_NAME = '{{ item }}'" | grep --quiet .
-      changed_when: false
+          output=$(iquest '%s' "select META_COLL_ATTR_VALUE where META_COLL_ATTR_NAME = 'ipc_UUID' and COLL_NAME = '{{ item }}'")
+          if [[ "$output" == *"CAT_NO_ROWS_FOUND"* ]]; then
+            echo "UUID not found for collection: {{ item }}"
+            exit 1
+          fi
       with_items:
         - /
         - /testing
@@ -52,6 +55,7 @@
         - /testing/trash
         - /testing/trash/home
         - /testing/trash/home/shared
+      changed_when: false
 
     - name: Test ensure CyVerse curated collection base collection exists
       ansible.builtin.command: ils /testing/home/shared/commons_repo/curated
